import jsPDF from "jspdf";
import type { CivicService } from "@/data/services";

export function generatePDF(service: CivicService): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Header
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("GOVERNMENT OF INDIA", pageWidth / 2, y, { align: "center" });
  y += 6;
  doc.text("(Placeholder — Not an Official Document)", pageWidth / 2, y, { align: "center" });
  y += 4;

  // Line
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Title
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(service.serviceName.toUpperCase(), pageWidth / 2, y, { align: "center" });
  y += 6;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Category: ${service.category}`, pageWidth / 2, y, { align: "center" });
  y += 10;

  // Line
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Instructions
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.text("Instructions: Fill all fields in BLOCK letters. Attach self-attested copies of required documents.", margin, y);
  y += 8;
  doc.text("This form is for preparation purposes only. Submit the completed form at your nearest government office.", margin, y);
  y += 12;

  // Form fields
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const fields = [
    "Full Name (As per Aadhaar)",
    "Father's / Husband's Name",
    "Date of Birth",
    "Gender",
    "Address",
    "District",
    "State",
    "PIN Code",
    "Mobile Number",
    "Aadhaar Number",
    "Purpose of Application",
  ];

  for (const field of fields) {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    doc.text(`${field}:`, margin, y);
    doc.line(margin + 60, y, pageWidth - margin, y);
    y += 10;
  }

  y += 5;

  // Documents table
  if (y > 220) {
    doc.addPage();
    y = 20;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("DOCUMENTS REQUIRED:", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  // Table header
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y - 4, contentWidth, 8, "F");
  doc.text("S.No.", margin + 2, y);
  doc.text("Document Name", margin + 18, y);
  doc.text("Attached (✓)", pageWidth - margin - 30, y);
  y += 8;

  service.documents.forEach((d, i) => {
    doc.text(`${i + 1}.`, margin + 2, y);
    doc.text(d.name, margin + 18, y);
    doc.rect(pageWidth - margin - 20, y - 4, 8, 6);
    y += 8;
  });

  y += 15;

  // Signature section
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("DECLARATION:", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("I hereby declare that the information provided above is true and correct to the best of my knowledge.", margin, y);
  y += 20;

  // Signature boxes
  const sigWidth = (contentWidth - 20) / 3;
  const sigY = y;

  ["Applicant Signature", "Witness Signature", "Officer Signature"].forEach((label, i) => {
    const x = margin + i * (sigWidth + 10);
    doc.rect(x, sigY, sigWidth, 25);
    doc.setFontSize(8);
    doc.text(label, x + sigWidth / 2, sigY + 30, { align: "center" });
  });

  y += 40;
  doc.setFontSize(7);
  doc.text("Date: _______________", margin, y);
  doc.text("Place: _______________", margin + 60, y);

  // Footer
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.text(
    "Generated by CIVIC AI — Form Discovery & Preparation Assistant. This is NOT an official government document.",
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" }
  );

  doc.save(`${service.id}-form.pdf`);
}
